apiVersion: v1
kind: Service
metadata:
  name: devops-task-service
spec:
  type: NodePort
  selector:
    app: devops-task
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000   # match containerPort above
      nodePort: 30080    # you can access app at this port
