apiVersion: apps/v1
kind: Deployment
metadata:
  name: logo-server
  namespace: default
  labels:
    app: logo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logo-server
  template:
    metadata:
      labels:
        app: logo-server
    spec:
      containers:
      - name: logo-server
        image: 716713632584.dkr.ecr.us-east-1.amazonaws.com/devops:latest
        ports:
        - containerPort: 3000   # change if your app uses a different port
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: logo-server-service
  namespace: default
  labels:
    app: logo-server
spec:
  type: LoadBalancer   # external access; change to NodePort/ClusterIP if needed
  selector:
    app: logo-server
  ports:
  - port: 80           # external service port
    targetPort: 3000   # container port (same as above)
